### ISSUE TITLE
페이지 내 Github 주소 변경

### ISSUE THREAD

**Issue by dodok8** [Svelte-Korea/learn.svelte.kr#15]
현재 깃헙 아이콘 클릭하면 <https://github.com/sveltejs/learn.svelte.dev>로 가는데 이를 한국어 저장소 주소로 바꾸고자 합니다.

**Comment by D0ri123** [comment]
현재 learn.svelte.jp에서는 GitHub 아이콘을 클릭하면 Svelte 공식 저장소로 이동하는 걸로 알고 있습니다! 공식 저장소는 주로 오픈 소스 기여와 이슈 트래킹, 보다 더 자세한 정보를 얻을 수 있는 곳인데요.
Svelte-Korea 저장소는 현재 Svelte 문서 번역에만 중점을 두고 있어서요..! 만약 튜토리얼 사용자가 Svelte에 대해 더 깊이 알고 싶거나 참여하고 싶은 경우에는 공식 저장소가 더 적합하다는 생각이 듭니다.

**Comment by D0ri123** [comment]
@dodok8 안녕하세요! 메인테이너 간 의견이 아직 최종적으로 확정되지 않아서요. 혹시 한국어 저장소 주소를 변경하려는 이유가 있으신지 알려주실 수 있을까요? 감사합니다 :)

**Comment by dodok8** [comment]
한국어 문서에서 기여를 하고 싶어서 깃헙 링크를 누르는 사람들의 경우, 깃헙 링크가 원본 문서로 열리면 거기서 여기 한국어 저장소로 오는 직접적인 링크가 없습니다.

반대의 경우(원본에 기여를 하고 싶은 경우)는 한국어 저장소 메인 리드미에 역주가 있어 바로 이동이 가능합니다.

**Comment by Jueun-Park** [comment]
처음엔 아무래도 좋다고 생각했긴 한데, 다시 생각해보니까 깃헙 링크가 learn (tutorial) 에 대한 링크니까 번역에 기여하고 싶은 사람을 모으는 데에는 바꾸는 것도 나을 것 같아요.

이건 다른 이야기이긴 한데, 홈페이지의 메인 로고에 써 있는 제목도 바꿀 수 있을지도 모르겠네요 ㅎㅎ
https://github.com/Svelte-Korea/learn.svelte.kr/blob/main/src/routes/%2Blayout.svelte#L17
여기인 것 같아요.

**Comment by D0ri123** [comment]
@dodok8 @Jueun-Park 그러면 깃헙 링크를 dodok8님이 해주신대로 merge하는 걸로 하겠습니다!! 
메인 로고 제목을 바꾼다면 LEARN.SVELTE.KR 이렇게 어떨까요? ㅎ.ㅎ 근데 DEV가 뭔가 나은 것 같기도 하구,, 주은님은 어떤 제목을 생각하신 걸까요?
![image](https://github.com/Svelte-Korea/learn.svelte.kr/assets/94590894/f43d95af-38e5-46df-9d79-59962a648aa0)

**Comment by Jueun-Park** [comment]
네 저는 learn.svelte.kr 생각했었습니다 ㅎㅎ 이 부분은 @dodok8 님께서 풀리퀘 올려주셨으니 dodok8님 의견 따라서 갈게요~
