### ISSUE TITLE
svelte 리드미 문서 업데이트 제안

### ISSUE THREAD

**Issue by D0ri123** [Svelte-Korea/learn.svelte.kr#21]
초기에 npm install 명령을 실행했을 때 "Fix the upstream dependency conflict, or retry"와 같은 오류로 인해 의존성 설치가 실패했습니다. 그래서 npm install --force 명령을 사용하여 강제로 설치를 시도했고, node scripts/create-common-bundle 명령으로 패키지를 압축했습니다.

그런데 이후에 npm dev 명령이 정상적으로 실행되지 않았습니다. 대신 npm run dev 명령을 사용하여 로컬에서 프로젝트를 성공적으로 동작시킬 수 있었습니다. 다른 분들은 리드미 문서대로 명령했을 때 아무런 이슈가 발생하지 않았는지 확인차 이슈 등록합니다~!

만약 한 분이라도 계신다면 리드미 문서를 업뎃해야할 것 같습니다. 🙇‍♀️

**Comment by dodok8** [comment]
리드미 문서대로 npm 이 아니라 pnpm 을 사용하셔도 똑같은 증세가 발생하시나요? 그리고 이 저장소 자체는 번역 저장소라, 코드 실행 자체에 대한 논의는 원본 저장소에서 진행하시는게 더 많은 도움을 얻을 수 있는 길이라 생각합니다.

 이와 별개로 문장 표현이 어색한 부분이 있어 일부 수정이 필요하다고 생각합니다.

**Comment by Jueun-Park** [comment]
- 실행 오류에 대한 이슈는 원본 레포에 등록해주세요!
- 리드미 번역 수정 제안은 본 레포에 따로 이슈를 등록해주세요~

---
그리고 저는 확실치는 않은데 리드미처럼 다음을 실행했을 때 문제 없이 동작했던 것 같아요 ...

```
node scripts/create-common-bundle
pnpm dev
```

첫째 줄 실행 시에 어떤 패키지가 없다고 떴었던 것 같기도 한데 `pnpm i` 로 해결했던 것 같기도 하고요... 잘 기억이 안 나네요
지금은 `pnpm dev`로 확인해가면서 번역 중입니다~

**Comment by dodok8** [comment]
`pnpm install` 이 안되는 경우, 왼도우 환경이시면 관리자 권한으로 열린 터미널에서 실행해보시길 바랍니다. 원인은 모르겠는데 pnpm이 관리자 권한 요구하는 경우가 있더라고요

**Comment by D0ri123** [comment]
헉 제가 해당 이슈는 체크하지 못했네요 🥲 익숙치 않은 기술언어라 pnpm 을 brew install해야 한다는걸 몰랐습니다..;; ㅎ 그래서 pnpm 을 설치한 이후에 리드미대로 실행시키니깐 정상적으로 동작하는걸 확인했습니다. 이 이슈는 close해두겠습니다...!!
