### ISSUE TITLE
원본 저장소에서 가져오기 가이드

### ISSUE THREAD

**Issue by dodok8** [Svelte-Korea/learn.svelte.kr#28]
오늘 보니깐 보안 경고가 왔던데 이런 패키지 업데이트에 필요한 요소를 포함해서, 원본 저장소에서 커밋을 가져오는 방법에 대한 가이드가 필요할 것 같습니다.

일단 현재 생각 중인건 git remote로 source를 원본 저장소로 추가 후에, merge 하는 형식입니다.

**Comment by dodok8** [comment]
현재 [제 저장소](https://github.com/dodok8/learn.svelte.kr/commit/6110e22c2838fab10bcdae3a24ba7562579e0e8f)에 아래 명령어로 최신본 받아올때 어떻게 되는지 볼 수 있습니다.

```
git remote add source https://github.com/sveltejs/learn.svelte.dev.git
git fetch source
git merge source/main
```

**Comment by Jueun-Park** [comment]
네 큰 문제 없어 보여서 그렇게 진행하면 될 것 같습니다
우선은 공개적인 가이드가 없어도 메인테이너끼리 상의 후 한 사람이 진행하고 내부에서 공유되면 되지 않을까 싶은데 어떠세요?

**Comment by dodok8** [comment]
넵 그럼 오늘 내로 PR 올리겠습니다

**Comment by Jueun-Park** [comment]
#32 와 연관 있을 것 같네요 (기여 가이드에 포함 가능한 내용)
여기를 닫고 그 쪽에서 논의해볼까요?
