### ISSUE TITLE
번역 활동 관련 문의

### ISSUE THREAD

**Issue by suhyeoonn** [Svelte-Korea/learn.svelte.kr#35]
안녕하세요~! 번역 활동 중 궁금한 점이 생겨 문의드려요!

### 1. PR merge
기여자가 직접 머지하면 될까요?? #32 내용보고 그렇게 이해했는데, 제 PR이(https://github.com/Svelte-Korea/learn.svelte.kr/pull/34) 승인은 되었지만 머지 버튼이 보이지 않아서요..!
별도 권한을 요청해야 하는지, 다른 분이 머지해주실 때까지 기다리면 되는지 궁금합니다!
![image](https://github.com/Svelte-Korea/learn.svelte.kr/assets/47198353/cea77ade-c31c-4d1c-bd54-fb4c0138d64d)

### 2. 일부 페이지만 번역 가능 여부
[04-Advanced SvelteKit/04-Advanced routing](https://learn.svelte.dev/tutorial/optional-params)은 5개의 페이지로 구성되어있는데,
- Optional parameters
- Rest parameters
- Param matchers
- Route groups
- Breaking out of layouts

혹시 이 중 `Optional parameters` 하나만 번역한다거나, 2개 정도로 일부만 번역 활동도 가능할까요??
페이지가 많을 경우 리뷰어 분들도 확인할 내용이 많아질거라 PR 단위를 작게 유지하는 편이 어떨까 싶어서요..!
만약 가능하다면 이슈 티켓 제목은 어떻게 생성하는 게 좋을지 알려주시면 감사하겠습니다!!

### 3. 이슈 티켓 레이블 추가
기여자는 이슈 티켓 생성은 가능하지만 레이블이나 Assignees 설정은 메인테이너분들이 따로 해주시는게 맞을까요??
머지와 마찬가지로 권한이 없어 설정이 안되는 것 같아서 문의드립니다!

**Comment by Jueun-Park** [comment]
1. 머지는 메인테이너만 가능합니다.
2. 네 가능합니다~ PR 제목에 표시만 잘 되면 좋을 것 같습니다
    - 티켓 제목은 우선 편하신 대로 적어 주시면 기여 가이드 작성 이후에 메인테이너들이 관리할 수 있을 것 같습니다. 그 전까지는 자유롭게 표시해 주시면 저희도 가이드 작성에 참고하겠습니다 😄 
3. 맞습니다~

cc. @D0ri123 @dodok8 
관련 내용을 CONTRIBUTING.md 에 추가하면 좋을 것 같습니다! #32

**Comment by D0ri123** [comment]
안녕하세요! 말씀해주신 내용은 CONTRIBUTING.md 파일에 반영될 것 같습니다. 
추가 의견이 있으시면 #32 이슈에서 자유롭게 말씀해주세요~!! 😄
해당 이슈는 close 하도록 하겠습니다~ 🙇‍♀️
