### ISSUE TITLE
01-svelte/02-reactivity, 03-props, 04-logic

### ISSUE THREAD

**Issue by HarunaMahjong** [Svelte-Korea/learn.svelte.kr#53]
## 번역 범위

- [x] 01-svelte/02-reactivity
- [x] 01-svelte/03-props
- [x] 01-svelte/04-logic

## 번역 내용

반응성, 프롭, 로직 관련 내용 전체

**Comment by dodok8** [comment]
메인테이너들끼리 의논해본 결과 한 PR에 올려주신 내용이 많아 검토하기가 너무 힘든 상황이라 PR 과 이슈를 닫으려고 합니다. `content/tutorial/` 의 서브폴더 단위보다는, 서브 폴더의 서브 폴더의 단위로 이슈를 작성해 주시거나 아니면 그 보다 더 작은 단위로 나눠 주시면 감사하겠습니다. 그 보다 큰 단위의 경우 맥락이 다른 여러 문서를 검토해야 하니 검토 시간이 너무 오래 걸릴 뿐더라 현재 메인테이너 분들의 사정상 그 많은 양을 다 검토하기가 힘든 상황입니다.

올려 주신 내용은 위 내용 단위로 별도 브랜치와 이슈, PR 로 나눠주시면 다시 검토해드리겠습니다. 관련 내용도 곧 `contributing.md` 및 이슈 템플릿, PR 템플릿에 업데이트 될 예정입니다.

다른 이슈인 #63, #55 도 같은 이유로 클로즈 처리하겠습니다.
