### ISSUE TITLE
번역 일관성 관리

### ISSUE THREAD

**Issue by Jueun-Park** [Svelte-Korea/learn.svelte.kr#8]
### 개요
- 장기 목표
- 번역의 일관성을 위함

### 해야 할 일
- 가이드 만들고 운영하기
  - 용어집(glossary)
  - 어조(tone)
- 원본 저장소 최신 커밋 따라가기

### 참고
- 스벨트 일본 문서
  - https://learn.svelte.jp
    - 어순 구성 참고
- 쿠버네티스 한국 문서
  - 문서화 README-ko.md https://github.com/kubernetes/website/blob/main/README-ko.md
  - 문서 한글화 가이드: https://kubernetes.io/ko/docs/contribute/localization_ko/
    - [한글화 용어집](https://kubernetes.io/ko/docs/contribute/localization_ko/#%ED%95%9C%EA%B8%80%ED%99%94-%EC%9A%A9%EC%96%B4%EC%A7%91)
  - i18n go template 제공

**Comment by dodok8** [comment]
`- 가이드 만들고 운영하기` 부분에 최신 튜토리얼 커밋 가져오는 내용을 추가해야 할 것 같습니다.
그리고 번역 가이드 만드는데 <https://learn.svelte.jp>를 참고할 수 있을 것 같습니다. 아무래도 영어보다는 일본어가 한국어 문법에 가깝기 때문에, 어순이나 문장기호가 한국어에 가까운 문장이 많습니다. 표현 같은 건 주의해서 봐야겠지만, 영어 문장형식을 그대로 한국어로 옮기는 번역보다는 한국어 문장 형식에 맞추는 번역이 더 자연스럽다 생각합니다.

**Comment by dodok8** [comment]
일단 제가 기존 작업본에서 사용했던 컨벤션입니다.

1. 원본은 <https://learn.svelte.dev>
2. 기존 원본 문장과 어순이 다르더라도 한국어 문장기호를 사용할 것.(과도한 괄호 사용 지양, `:`와 `-` 사용하지 않기)
3. 어순 구상에 어려움이 있을 경우, <https://learn.svelte.jp> 참고
4. 주어와 복수형 표기가 생략이 가능한 경우 생략해서 자연스러운 문장 만들기
5. Svelte 와 SvelteKit은 고유명사이므로 원문 그대로 표기
6. 스벨트에서 만든 조어의 경우 음차 표기, 단 처음 쓰이거나 _강조_ 가 되어 있는 경우 `음차(원본)` 형식으로 펴기
7. 한국어 번역어가 있는 경우에도 제목에 쓰인 경우에는 `음차(원본)` 형식 표기


이 중에서 지금 이 저장소 컨벤션과 충돌이 있는 건 2, 5, 6, 7 인데 이 부분을 정확히 명시하면 좋겠습니다.

**Comment by Jueun-Park** [comment]
@dodok8 좋은 의견 감사드립니다.

- jp 참고는 기존부터 생각하고 있었는데, 구체적인 참고 아이디어 주셔서 도움이 됩니다.
  - 본 이슈 글 '참고' 란에 업데이트 하였습니다.
- 기존 사용했던 컨벤션을 주셔서 큰 도움이 될 것 같습니다. 다만 5번에 대해서만 의견이 있는데요,
  - 'Svelte', 'SvelteKit'은 다음 이유 때문에 '스벨트', '스벨트킷'으로 표기하는 것을 주장합니다.
    - 한국어 문장을 읽어나가는 데에 어려움이 없이 편하다
    - 오히려 고유명사이므로 외래어 표기법을 반영해 한글로 표기하는 것이 어색하지 않다
    - 한국어 검색에 잘 걸릴 수 있다
    - [쿠버네티스 문서 용어 한글화 가이드](https://kubernetes.io/ko/docs/contribute/localization_ko/#%EC%9A%A9%EC%96%B4-%ED%95%9C%EA%B8%80%ED%99%94-%EA%B0%80%EC%9D%B4%EB%93%9C) 등 기존 사례가 있다

검토해보시고 의견 주시면 초안 작성해보겠습니다 😄

**Comment by dodok8** [comment]
한국어 검색은 생각 못했네요. 그럼 그 부분은 스벨트와 스벨트킷으로 변경해서 다시 커밋 올리겠습니다. 감사합니다.

**Comment by Jueun-Park** [comment]
- [번역 가이드](https://github.com/Svelte-Korea/learn.svelte.kr/wiki/%EB%B2%88%EC%97%AD-%EA%B0%80%EC%9D%B4%EB%93%9C)
  - 2024년 2월 12일자로 초안 작성

@dodok8 #12 는 시간 날 때 천천히 리뷰 보겠습니다!

**Comment by dodok8** [comment]
번역 가이드라인을 위키로 관리하는 것보단 저장소 내  md 파일로 관리하는 방안에 대해선 어떻게 생각하시나요?

**Comment by Jueun-Park** [comment]
md 파일이 더 좋다고 생각합니다. 다만 파일명을 정하지 못해서 우선 위키에 작성했는데요, `CONTRIBUTING.md` 로 관리하면 되려나요?

**Comment by D0ri123** [comment]
#32 에서 이어서 논의
